# Generated by Django 5.1 on 2024-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
    ]
