# Generated by Django 5.1 on 2024-08-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('subcategory_image', models.CharField(default='abc', max_length=100)),
                ('subcategory_description', models.TextField()),
                ('category_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminCategory.category')),
            ],
            options={
                'db_table': 'tbl_subcategory',
            },
        ),
    ]
