# Generated by Django 5.1 on 2024-09-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminState', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('state_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminState.state')),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
    ]
