# Generated by Django 5.1 on 2024-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminCity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
