# Generated by Django 5.1 on 2024-09-23 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminProduct', '0002_product_subcategory_id'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminProduct.product')),
            ],
            options={
                'db_table': 'tbl_items',
            },
        ),
    ]
