# Generated by Django 5.1 on 2024-08-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.CharField(default='abc', max_length=100)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
