# Generated by Django 5.1 on 2024-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('slider_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_button_url', models.URLField(blank=True, null=True)),
                ('slider_image', models.CharField(default='image', max_length=100)),
            ],
            options={
                'db_table': 'tbl_slider',
            },
        ),
    ]
