# Generated by Django 5.1 on 2024-09-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProduct', '0001_initial'),
        ('AdminSubCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminSubCategory.subcategory'),
        ),
    ]
