# Generated by Django 5.1 on 2024-10-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_shipping_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_charge',
            new_name='shipping_charge_order',
        ),
    ]
