# Generated by Django 5.1 on 2024-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_shipping_charge_order_shipping_charge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finaltotal_charge_order',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_order',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
